name: "Sample Action"
description: "github-action-demoから呼び出すサンプルのAction"
inputs:
  variable1:
    description: "入力1"
    required: true
    default: "金渕"
outputs:
  ouput1:
    description: "出力1"
    value: ${{ steps.random-num-gen.outputs.num-output1 }}
runs:
  using: "composite"
  steps:
    - id: echo-input-value
      run: echo ${{ inputs.valiable1 }}
      shell: bash
    - id: random-num-gen
      run: echo "num-output1=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - id: run-shell-script
      run: shellscripts/hello.sh
      shell: bash
