name: Switching
on:
  push:
    branches:
      - main
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
  debug_run:
    needs: setup
    if: ${{ github.ref_name != 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: running Python Script Debug
        run: python python/sample_env.py
        env:
          FIRST_NAME: "開発用"
          LAST_NAME: "環境変数"
  prod_run:
    needs: setup
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: running Python Script Prod
        run: python python/sample_env.py
        env:
          FIRST_NAME: ${{ secrets.FIRST_NAME }}
          LAST_NAME: ${{ secrets.LAST_NAME }}